CREATE TABLE  IF NOT EXISTS `#__atlete` (
  `id` varchar(200) NOT NULL COMMENT ''Id'',
  `first_name` varchar(50) DEFAULT NULL COMMENT ''First name'',
  `last_name` varchar(50) DEFAULT NULL COMMENT ''Last name'',
  `date_of_birth` date DEFAULT NULL COMMENT ''Date of birth'',
  `num_tes` varchar(8) DEFAULT NULL COMMENT ''Fidal id'',
  `num_tes_datetime_confirmed` datetime DEFAULT NULL COMMENT ''Fidal confirmation datetime'',
  `sex` varchar(1) DEFAULT NULL,
  `citizenship` varchar(50) DEFAULT NULL COMMENT ''Citizenship'',
  `address` varchar(50) DEFAULT NULL COMMENT ''Address'',
  `zip` varchar(5) DEFAULT NULL COMMENT ''Zip'',
  `city` varchar(50) DEFAULT NULL COMMENT ''City'',
  `phone` varchar(50) DEFAULT NULL COMMENT ''Phone'',
  `email` varchar(50) DEFAULT NULL COMMENT ''Email'',
  `other_num_tes` varchar(20) DEFAULT NULL COMMENT ''Other federation number'',
  `other_ass_name` varchar(50) DEFAULT NULL COMMENT ''Other federation name'',
  `registration_datetime` datetime DEFAULT NULL COMMENT ''Regsitration date time'',
  `payment_type` enum(''bank_transfer'',''money_order'',''paypal'') DEFAULT NULL COMMENT ''Payment type'',
  `payment_datetime` datetime DEFAULT NULL COMMENT ''Payment datetime, in null not sucesfull'',
  `payment_fname` varchar(50) DEFAULT NULL COMMENT ''Payment file name'',
  `payment_confirm_datetime` datetime DEFAULT NULL COMMENT ''Payment confirm date time, in null not confirmed'',
  `medical_certificate_fname` varchar(50) DEFAULT NULL COMMENT ''Medical certificate file name'',
  `medical_certificate_datetime` datetime DEFAULT NULL COMMENT ''Medical certificate date time'',
  `medical_certificate_confirm_datetime` datetime DEFAULT NULL COMMENT ''Medical certificate confirm date time, if null not confirmed'',
  `game_card_fname` varchar(50) DEFAULT NULL COMMENT ''Game card file name'',
  `game_card_datetime` datetime DEFAULT NULL COMMENT ''Game card upload date time'',
  `pectoral` int(11) DEFAULT NULL COMMENT ''Pectoral number'',
  `removed` tinyint(1) NOT NULL DEFAULT ''0'' COMMENT ''Removed items'',
  `group_reference_id` varchar(200) DEFAULT NULL COMMENT ''ID of group reference'',
  PRIMARY KEY (`id`,`removed`) COMMENT ''Id must be unique'',
  KEY `first_name` (`first_name`),
  KEY `last_name` (`last_name`),
  KEY `date_of_birt` (`date_of_birth`),
  KEY `phone` (`phone`),
  KEY `email` (`email`),
  KEY `city` (`city`),
  KEY `num_tes` (`num_tes`),
  KEY `pectoral` (`pectoral`),
  KEY `payment_confirm_datetime` (`payment_confirm_datetime`),
  KEY `medical_certificate_confirm_datetime` (`medical_certificate_confirm_datetime`),
  KEY `group_reference_id` (`group_reference_id`)
  ) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='Atlete table';


CREATE TABLE  IF NOT EXISTS`#__fidal_fella` (
  `num_tes` VARCHAR(8) NOT NULL COMMENT 'Card number',
  `categ` VARCHAR(4) NULL COMMENT 'Category',
  `cod_soc` VARCHAR(5) NULL COMMENT 'Code society',
  `denom` VARCHAR(50) NULL COMMENT 'Society name',
  `dat_mov` DATE NULL COMMENT 'Date',
  `cogn` VARCHAR(50) NULL COMMENT 'Last name',
  `nome` VARCHAR(50) NULL COMMENT 'First name',
  `dat_nas` DATE NULL COMMENT 'Date of birth',
  `stran` VARCHAR(1) NULL COMMENT 'Stranger',
  `cod_reg` VARCHAR(3) NULL COMMENT 'Region code',
  PRIMARY KEY (`num_tes`) ,
  KEY `nome` (`nome`),
  KEY `cogn` (`cogn`),
  KEY `dat_nas` (`dat_nas`)
)
ENGINE = InnoDB
COMMENT = 'Data of fidal fella';